title: Lorenzo Salgado # your name (or website title) here
logo: "https://media-exp2.licdn.com/dms/image/C4E03AQGM6wG-kTor5A/profile-displayphoto-shrink_200_200/0/1652716880347?e=1660176000&v=beta&t=ODHL6nHnSWVOsxvN7u1nl4ZHb25GE-FZ6srCwhYxtgM" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.S. Mechanical Engineering, Tufts University 2021 
  <br><br>
  Technical Writer | Education Advocate
  <br><br>
  Somerville, MA
  <br><br>
  <a href="pdf/ls_resume_sp22.pdf" target="_blank">-Resume [Updated June, 2022].<a>
  <br><br>  
  <a href="https://www.linkedin.com/in/lorenzo-salgado/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
