title: Lorenzo Salgado # your name (or website title) here
logo: "https://media-exp1.licdn.com/dms/image/C5603AQHMqtEXjUTrnA/profile-displayphoto-shrink_800_800/0/1622994879151?e=1629331200&v=beta&t=TMTMdxVyQNeDc1Up2NhZThTlNTrctWIt6RrpM0unP4w" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.S. Mechanical Engineering, Tufts University 2021 
  <br><br>
  Technical Writer | 3D Printing Hobbyist | Education Advocate
  <br><br>
  <a href="https://www.linkedin.com/in/lorenzo-salgado/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
