title: Lorenzo Salgado # your name (or website title) here
logo: "https://media.licdn.com/dms/image/C4E03AQEYw0BuOt2snA/profile-displayphoto-shrink_400_400/0/1667947866378?e=1715817600&v=beta&t=Z4DBpEaWudhU4wR2ReOs8oMTzYtFI37drvIjTZfjH14" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.S. Mechanical Engineering, Tufts University 2021 
  <br><br>
  Technical Writer | Education Advocate
  <br><br>
  Somerville, MA
  <br><br>
  <a href="pdf/ls_resume_sp24.pdf" target="_blank">-Resume [Updated February, 2024].<a>
  <br><br>  
  <a href="https://www.linkedin.com/in/lorenzo-salgado/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
